acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('reprofile/', views.reprofile, name="reprofile"),
    path('repass/', views.repass, name="repass"),
    path('delete/', views.delete, name="delete"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('write/<bpk>', views.write, name="write"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('kbm/', include('kbms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kbms/urls.py
from django.urls import path
from . import views

app_name = "kbm"
urlpatterns = [
    path('info/', views.info, name="info"),
    path('books/', views.books, name="books"),
    path('book1/', views.book1, name="book1"),
    path('book2/', views.book2, name="book2"),
    path('book3/', views.book3, name="book3"),

]

acc/models.py
from importlib.resources import contents
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    content = models.TextField(blank=True)
    point = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y")

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

board/models.py
from asyncore import write
from django.db import models
from acc.models import User
from django.utils import timezone
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField(blank=True)
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]} ..."
        return self.content

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

kbms/models.py
from django.db import models

# Create your models here.

acc/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.hashers import check_password
# Create your views here.

def index(request):
    return render(request,"acc/index.html")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(request, u)
            return redirect("acc:index")
        else:
            pass
    return render(request, "acc/login.html")

def logout_user(request):
    logout(request)
    return redirect("acc:index")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("con")
        upic = request.FILES.get("pic")
        try:
            User.objects.create_user(username=un, password=up, content=uc, pic=upic)
            return redirect("acc:login")
        except:
            pass
    return render(request, "acc/signup.html")

def profile(request):
    return render(request, "acc/profile.html")

def reprofile(request):
    if request.method == "POST":
        u = request.user
        um = request.POST.get("umail")
        uc = request.POST.get("ucon")
        up = request.FILES.get("upic")
        u.email , u.content = um , uc
        if up:
            u.pic.delete()
            u.pic = up
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/reprofile.html")

def repass(request):
    if request.method == "POST":
        u = request.user
        cp = request.POST.get("fpass")
        if check_password(cp, u.password):
            np = request.POST.get("lpass")
            u.set_password(np)
            u.save()
            return redirect("acc:login")
        else:
            pass
    return redirect("acc:profile")

def delete(request):
    u = request.user
    p = request.POST.get("pass")
    if check_password(p, u.password):
        request.user.delete()
        return redirect("acc:login")
    else:
        return redirect("acc:profile")

board/views.py
from django.shortcuts import redirect, render

from acc.models import User

from .models import Board, Reply
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    page = request.GET.get("page", 1)
    kw = request.GET.get("kw","")
    cate = request.GET.get("cate","")
    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.none()
    else:
        b = Board.objects.all()
    pag = Paginator(b, 5)
    obj = pag.get_page(page)
    
    

    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw
    }
    return render(request, "board/index.html", context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all() #댓글 다 나와
    context = {
        "b" : b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass
    return redirect("board:index")

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s,writer=request.user,content=c).save()
        return redirect("board:index")

    return render(request, "board/create.html")

def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if request.user != b.writer:
        pass
        return redirect("board:index")

    context = {
        "b" : b
    }
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s, c
        b.save()
        return redirect("board:detail", bpk)
    return render(request, "board/update.html", context)

def write(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("content")
    Reply(b=b,replyer=request.user,comment=c).save()
    return redirect("board:detail", bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    else:
        pass
    return redirect("board:detail", bpk)

kbms/views.py
from django.shortcuts import render

# Create your views here.
def info(request):
    return render(request, "kbms/info.html")

def books(request):
    return render(request, "kbms/books.html")

def book1(request):
    return render(request, "kbms/book1.html")

def book2(request):
    return render(request, "kbms/book2.html")

def book3(request):
    return render(request, "kbms/book3.html")

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    <h1>곽부모교수님의 사이트</h1>
    <h2>Professor Kawk's site</h2>

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>LOGIN PAGE</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mt-5">
            <input type="text" class="form-control" placeholder="INPUT USERNAME" name="uname">
            <input type="password" class="form-control mt-4 mb-4" placeholder="INPUT PASSWORD" name="upass">

            <div class="text-end">
                <button class="btn btn-dark btn-lg">로그인</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
<h1><b>프로필</b></h1>

<div class="row">
    <div class="col-sm-4">
        <div class="text-center">
            <img src="{{ user.getpic }}" height="250px">
            <div><a href="{% url 'acc:reprofile' %}"><button class="btn btn-dark mt-5">프로필 수정</button></a></div>
            <button type="button" class="btn btn-danger mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
                계정 삭제
            </button>
            
        </div>
    </div>
    <div class="col sm-8">
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{ user.username }}" disabled class="form-control" style="font-weight: bold;">
        </div>
        <div class="mb-3">
            <label class="form-label">POINT</label>
            <input type="text" value=" {{ user.point }}P" style="font-weight: bold;" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">EMAIL</label>
            <input type="text" value="{{ user.email }}" style="font-weight: bold;" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.content }}</textarea>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">계정 삭제 알림창</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'acc:delete' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="password" placeholder="INPUT CURRENT PASSWORD" class="form-control" name="pass">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-danger">삭제</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/acc/reprofile.html
{% extends 'base.html' %}
{% block con %}
<h1><b>프로필수정</b></h1>

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="mb-3 mt-5">
    <label class="form-label">USERNAME</label>
    <input type="text" value="{{user}}" disabled class="form-control">
</div>
<div class="mb-3">
    <label class="form-label">EMAIL</label>
    <input type="text" value="{{user.email}}" class="form-control" name="umail">
</div>
<div class="mb-3">
    <label class="form-label">CONTENT</label>
    <textarea class="form-control" name="ucon">{{user.content}}</textarea>
</div>
<div class="mb-3">
    <label class="form-label">USERPIC</label>
    <input type="file" class="form-control" name="upic">
</div>
<div class="text-end">
    <a href="{% url 'acc:profile' %}" class="btn btn-dark">취소</a>
    <button class="btn btn-dark">변경</button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        패스워드 변경
    </button>
</div>
</form>




    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>패스워드 변경창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:repass' %}">
                {% csrf_token %}
                <div class="modal-body">
                    
                    <div class="container">
                        
                        <input type="password" class="form-control" placeholder="INPUT CURRENT PASSWORD" name="fpass">
                        <input type="password" class="form-control mt-3" placeholder="INPUT NEW PASSWORD" name="lpass">
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-primary">변경</button>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}
<h1><b>회원가입</b></h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3 mt-5">
        <label class="form-label">USERNAME</label>
        <input type="text" class="form-control" name="uname">
    </div>
    <div class="mb-3">
        <label class="form-label">PASSWORD</label>
        <input type="password" class="form-control" name="upass">
    </div>
    <div class="mb-3">
        <label class="form-label">CONTENT</label>
        <textarea class="form-control" name="con"></textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">USERPIC</label>
        <input type="file" class="form-control" name="pic">
    </div>
    <div class="mt-4 text-end">
        <button class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
    </div>
</form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>KBM</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>

        {% if user.is_authenticated %}
        <!-- 인증된 사용자라면 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; font-weight: bold; font-size: 20px;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    KBM
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'kbm:info' %}">INFO</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'kbm:books' %}">BOOKS</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Disabled</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>


        {% else %}
        <!-- 익명의 사용자라면 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; font-weight: bold; font-size: 20px;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        {% endif %}
        

        <div class="container mt-5 mb-5">
            {% block con %}

            {% endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글 작성</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" class="form-control" name="sub">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" style="height: 150px;" name="con"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>{{ b.subject }}</b></h1>
    <div class="row mt-4">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 180px;" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="90%">
            <div class="mt-3">
                <h5>written by <b>{{ b.writer }}</b></h5>
            </div>
            <div class="text-end mt-3">
                {{ b.pubdate | date:'Y년 m월 d일 H:i' }}
            </div>
        </div>
    </div>

    <div class="text-end mt-4">
        <a class="btn btn-dark" href="{% url 'board:index' %}">글 목록</a>

        {% if user == b.writer %}
        <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">글 수정</a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            게시글 삭제
        </button>
        {% endif %}
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}"><button type="button" class="btn btn-danger">삭제</button></a>
                </div>
            </div>
        </div>
    </div>
    <hr>

    <form action="{%url 'board:write' b.id%}" method="post">
        {% csrf_token %}
    <div class="row mt-3 mb-5">
        
            <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="댓글을 입력하세요.." name="content">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-dark" style="width: 100%;">댓글 작성</button>
            </div>
        
    </div>
    </form>
    

    {% if rset %}
        {% for i in rset %}
            <div class="row mt-4">
                <div class="col-sm-3">
                    <img src="{{ i.replyer.getpic }}" width="100%">
                    <div class="text-center"><b>{{ i.replyer }}</b></div>
                    
                </div>
                <div class="col-sm-9">
                    <textarea class="form-control" style="height: 130px;" disabled>{{ i.comment }}</textarea>
                    <div class="text-end">
                        {% if user == i.replyer %}
                        <a class="btn btn-danger mt-3" href="{% url 'board:dreply' b.id i.id %}">댓글 삭제</a>
                        {% endif %}
                    </div>
                </div>
            </div>    
        {% endfor %}
    {% else %}
        <h3>첫번째 댓글을 달아주세요</h3>
    {% endif %}
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <h1><b>게시판</b></h1>

    <div class="text-end">
        <a href="{% url 'board:create' %}"><button class="btn btn-dark">글쓰기</button></a>
    </div>

    <table class="table mt-4 table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% if bset %}
                {% for i in bset %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url 'board:detail' i.id %}" class="sub">{{ i.subject }}</a></td>
                    <td>{{ i.summary }}</td>
                    <td>{{ i.writer }}</td>
                    <td>0</td>
                </tr>
                {% endfor %}
            {% else %}
                {% if kw %}
                    <tr>
                        <th colspan="5">검색 결과가 없습니다</th>
                    </tr>
                {% else %}
                    <tr>
                        <th colspan="5">첫번째 게시글을 작성해주세요</th>
                    </tr>
                {% endif %}
            {% endif %}
        </tbody>
    </table>
    <form>
        <div class="row mt-5">
            
            <div class="col-sm-2">
            <select name="cate" class="form-select">
                <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
            </select>
            </div>
            <div class="col-sm-9">
            <input type="text" name="kw" value="{{ kw }}" class="form-control">
            </div>
            <div class="col-sm-1">
            <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
            
        </div>
    </form>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if bset.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'board:index' %}?page=1&kw={{kw}}&cate={{cate}}">처음</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&kw={{kw}}&cate={{cate}}">이전</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#" >처음</a>
            </li>
            <li class="page-item">
                <a class="page-link disabled" href="#" >이전</a>
            </li>
            {% endif %}
            {% for i in bset.paginator.page_range %}
            {% if i >= bset.number|sub:4 and bset.number|add:5 >= i %}
            <li class="page-item"><a class="page-link {% if bset.number == i %}active{% endif %}" href="{% url 'board:index' %}?page={{ i }}&kw={{kw}}&cate={{cate}}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if bset.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&kw={{kw}}&cate={{cate}}">다음</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&kw={{kw}}&cate={{cate}}">마지막</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#">다음</a>
            </li>
            <li class="page-item">
                <a class="page-link disabled" href="#">마지막</a>
            </li>
            {% endif %}
        </ul>
    </nav>

      <style>
        .sub {
            text-decoration: none;
            font-weight: bold;
            color: black;
            font-size: 16px;
        }
        .sub:hover {
            color: gray;
        }

      </style>
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
<h1><b>게시글수정</b></h1>

<form method="post">
    {% csrf_token %}
    <div class="mb-3 mt-5">
        <label class="form-label">SUBJECT</label>
        <input type="text" class="form-control" value="{{ b.subject }}" name="sub">
    </div>
    <div class="mb-3">
        <label class="form-label">WRITER</label>
        <input type="text" class="form-control" disabled value="{{ b.writer }}">
    </div>
    <div class="mb-3">
        <label class="form-label">CONTENT</label>
        <textarea class="form-control" style="height: 150px;" name="con">{{ b.content }}</textarea>
    </div>
    <div class="text-end mt-3">
        <button class="btn btn-dark">수정</button>
    </div>
</form>
{% endblock %}

templates/kbms/books.html
{% extends 'base.html' %}
{% block con %}
<h1><b>INFO</b></h1>
<div class="row mt-3">
    <div class="card" style="width: 18rem;">
        <img src="/media/한국어문형러.png" class="card-img-top" style=" height: 70%;">
        <div class="card-body">
            <h5 class="card-title">비즈니스 한국어 문형: 러시아어권 학습자를 위하여</h5>
            <a href="{% url 'kbm:book1' %}" class="btn btn-primary">자세한 설명</a>
        </div>
    </div>
    <div style="width: 50px;" class="공백"></div>
    <div class="card" style="width: 18rem;">
        <img src="/media/한국어문형영.png" class="card-img-top" style=" height: 70%;">
        <div class="card-body">
            <h5 class="card-title">비즈니스 한국어 문형: 영어권 학습자를 위하여</h5>
            <a href="{% url 'kbm:book2' %}" class="btn btn-primary">자세한 설명</a>
        </div>
    </div>
    <div style="width: 50px;" class="공백"></div>
    <div class="card" style="width: 18rem;">
        <img src="/media/한국어말하기.png" class="card-img-top" style=" height: 70%;">
        <div class="card-body">
            <h5 class="card-title">초급 한국어 말하기 평가</h5>
            <a href="{% url 'kbm:book3' %}" class="btn btn-primary">자세한 설명</a>
        </div>
    </div>
    <div style="width: 50px;" class="공백"></div>
</div>
{% endblock %}

templates/kbms/info.html
{% extends 'base.html' %}
{% block con %}
<h1><b>INFO</b></h1>
<div class="row mt-3">
    <div class="col-sm-3">사진</div>
    <div class="col-sm-9">설명</div>
</div>
{% endblock %}